/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ca.bcit.comp2526.a2b;

import ca.bcit.comp2526.a2b.simulation.behavior.GraphicBehavior;
import ca.bcit.comp2526.a2b.simulation.behavior.GraphicBehavior.NullGraphicBehavior;
import ca.bcit.comp2526.a2b.simulation.behavior.StaticGraphicBehavior;
import ca.bcit.comp2526.a2b.graphic.ColorGraphic;
import java.awt.Color;
import javax.swing.InputVerifier;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JSpinner;

/**
 *
 * @author Jeremy Wildsmith
 */
public class GraphicBehaviorConfiguration extends JDialog {

    private GraphicBehavior behavior = new NullGraphicBehavior();

    /**
     * Creates new form GraphicBehaviorConfiguration
     * @param owner The owner of the dialog box.
     */
    public GraphicBehaviorConfiguration(JDialog owner) {
        super(owner);
        initComponents();

        InputVerifier iv = new InputVerifier() {
            @Override
            public boolean verify(JComponent input) {
                if (input instanceof JSpinner) {
                    JSpinner subject = (JSpinner) input;

                    try {
                        Integer i = Integer.valueOf(subject.toString());

                        return i >= 0 && i <= 255;
                    } catch (NumberFormatException e) {
                        return false;
                    }
                }

                return false;
            }
        };

        colorRed.setInputVerifier(iv);
        colorGreen.setInputVerifier(iv);
        colorBlue.setInputVerifier(iv);
    }

    /**
     * Gets the current graphical behavior.
     * @return The current graphical behavior.
     */
    public GraphicBehavior getGraphicBehavior() {
        return behavior;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        useBehavior = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        colorRed = new javax.swing.JSpinner();
        colorGreen = new javax.swing.JSpinner();
        colorBlue = new javax.swing.JSpinner();
        previewColourPanel = new javax.swing.JPanel();

        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);

        useBehavior.setText("Use Behavior");
        useBehavior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useBehaviorActionPerformed(evt);
            }
        });

        jLabel1.setText("Colour (RGB)");

        colorRed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rgbColorChanged(evt);
            }
        });

        colorGreen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rgbColorChanged(evt);
            }
        });

        colorBlue.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rgbColorChanged(evt);
            }
        });

        previewColourPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout previewColourPanelLayout = new javax.swing.GroupLayout(previewColourPanel);
        previewColourPanel.setLayout(previewColourPanelLayout);
        previewColourPanelLayout.setHorizontalGroup(
            previewColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        previewColourPanelLayout.setVerticalGroup(
            previewColourPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(useBehavior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(colorRed, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addComponent(previewColourPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(colorRed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorGreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(previewColourPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(useBehavior)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Static Colour", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Handles when RGB color was changed.
     * @param evt Jave event.
     */
    private void rgbColorChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rgbColorChanged

        previewColourPanel.setBackground(new Color(Integer.valueOf(colorRed.getValue().toString()),
                Integer.valueOf(colorGreen.getValue().toString()),
                Integer.valueOf(colorBlue.getValue().toString())));
    }//GEN-LAST:event_rgbColorChanged

    /**
     * Behavior for use color button.
     * @param evt The java awt event.
     */
    private void useBehaviorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useBehaviorActionPerformed
        behavior = new StaticGraphicBehavior(new ColorGraphic(new Color(Integer.valueOf(colorRed.getValue().toString()),
                Integer.valueOf(colorGreen.getValue().toString()),
                Integer.valueOf(colorBlue.getValue().toString()))));

        this.setVisible(false);
    }//GEN-LAST:event_useBehaviorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner colorBlue;
    private javax.swing.JSpinner colorGreen;
    private javax.swing.JSpinner colorRed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel previewColourPanel;
    private javax.swing.JButton useBehavior;
    // End of variables declaration//GEN-END:variables
}
